# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

name: Bundling

jobs:
  forecasts:
    runs-on: ubuntu-latest #efi-cirrus
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      OSN_KEY: ${{ secrets.OSN_KEY }}
      OSN_SECRET: ${{ secrets.OSN_SECRET }}
    container:
      image: ghcr.io/boettiger-lab/k8s@sha256:fd02edfb4318afe022f8a732a99d93df7127dadb2bb4e208e36a86f96c2f45c6
      options: --user root
    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: |
          sudo sed -i '/r2u/d' /etc/apt/sources.list.d/*.list 2>/dev/null || true
          R -e "update.packages(ask=FALSE, checkBuilt=TRUE, lib='/usr/lib/R/site-library', repos='https://cloud.r-project.org')"
          R -e "options(repos = c(CRAN = 'https://cloud.r-project.org')); install.packages(c('future.apply', 'progressr', 'minioclient', 'bench', 'glue', 'fs', 'tidyverse', 'yaml', 'duckdb'))"

      - name: Bundle forecasts
        run: r submission_processing/bundled_forecasts.R

      # - name: Bundle summaries
      #   run: r submission_processing/bundled_summaries.R


